

services:
  app:
    build: .
    container_name: php_app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: empresa_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
